### ISSUE TITLE
About "testFilter" option

### ISSUE THREAD

**Issue by LancerComet** [HuddleEng/Muppeteer#32]
I want to make muppeteer run `**/*.js` files, but now I can't because:

https://github.com/HuddleEng/Muppeteer/blob/529f6695871e686c409408bc74121cced0c9fa5c/lib/test-launcher.js#L94

It seems that if you have configured the option `testFilter: '.js'` it only runs 'test.js' file.

I don't understand why it is designed in this way, is there anyway to run `**/*.js` files?

**Comment by gidztech** [comment]
Yes, you’re correct. I’m going to make improvements in this area when I’m back from my trip. The project was originally designed to solve a specific criteria for us and then I slowly open sourced it, so there’s a bit more work needed.

**Comment by gidztech** [comment]
I've made some changes so you can now use a new `testPathPattern` property, which supports glob pattern. So you can do something like `path/tests/**/*.bla.js`. 

The `testDir` and `testFilter` still exist as fallback and will be used if `testPathPattern` isn't provided. The `testFilter` has been updated to support both Regex matching on the file name or substring matching on file name (any part of file name, not last 7 characters). 

This **should** be working 1.2.2 release, which I just pushed. I'm still yet to add more test coverage to the project (bad on my part).

**Slight breaking change to test launcher:**
`ConfigureLauncher` is now async so you need to await for the returned function, then you await the `launch` call as before. e.g.

```javascript
const launcher = await ConfigureLauncher({
      ...
);

await launcher.launch();
```

In this release I also attempted to introduce Chrome version pinning where you can specify the Chrome version you want to use with `dockerChromeVersion` config option. The launcher will try and download the version from the repo and build container. This is instead of always using latest version, which could break tests unexpectedly.

**Comment by LancerComet** [comment]
Thanks for your work!

**Comment by gidztech** [comment]
I'll close this issue. If you have any problems, feel free to re-open.
